# Generated by Django 3.2.7 on 2021-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('translation', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('A1', 'Beginer'), ('A2', 'Pre-Intermediate'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced')], max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
